### ISSUE TITLE
How do I put it into Synapse X?

### ISSUE THREAD

**Issue by Egemenbdk** [soapware/synx#1]
I tried putting the folder into the bin/ace folder named as "theme-KRNL" but it never worked, then I tried copy and pasting the code inside of the github download to a random js folder in bin/ace and trying that theme but it still didn't work. Please help.

**Comment by 7x9z** [comment]
It just goes into the folder "bin". Just drop it in there. SMH

**Comment by xn1781** [comment]
cant still find where do i put the .tff lol

**Comment by 7x9z** [comment]
add pull#2932 and i'll help u

**Comment by soapware** [comment]
> I tried putting the folder into the bin/ace folder named as "theme-KRNL" but it never worked, then I tried copy and pasting the code inside of the github download to a random js folder in bin/ace and trying that theme but it still didn't work. Please help.

holy shit you need to download the `theme_wpf.json` and replace the one in `synapse/bin`

**Comment by soapware** [comment]
> cant still find where do i put the .tff lol

The ttf file is a font file retard
